name: Hello World Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Say Hello World
        run: echo "Hello World!"
