name: Using Secrets Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  use-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Access and Print Secret
        # Access the secret via environment variables
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
        run: |
          echo "Using a secret key (hidden in logs)"
          echo "${API_KEY}" > /dev/null  # Do not log the value
